DLS-9402 | Fix partial accounts by introducing soft deletion of enrolments
hmrc/help-to-save pull request #267
Opened 2023-12-09 15:57 UTC by mahesh-hmrc

2023-12-11 16:31 UTC, lutnos reviewed
We need to generate audit events for each change.  The undo delete operation needs document IDs and we currently have no way of obtaining them.  The audit event ought to contain the IDs of all documents updated by an undelete, this could then be used when undoing deletes.

There are also untidy ends around the check on NINOs, for example when undoing a delete, the check only makes sure that something with that NINO exists, not necessarily the right documentID.

Again the document IDs from the BulkWriteResult are not sufficient, because we dio not know which are associated with which NINO.

I would suggest using the initial find to produce a complete list of NINOs with document IDs.  That could perhaps be audited.  Then best to bulk update using that list.  Do we then need to check the BulkWriteResult for any possible partial success - I am not clear.

I started an implementation of this myself, FWIW, but it got bogged down in converting an EitherT.  This may not be the best approach anyway.  On branch dave/DLS-9402/audit-soft-deletes, does not compile

2023-12-13 10:49 UTC, lutnos reviewed
@mahesh-hmrc 

It should be quite simple to audit undo of delete, because the document ID is present in the config.

But for delete, it is more tricky.  What I would suggest is to use the initial find() to augment the config with document Ids.  The new "config" with IDs can be passed out for delete instead.  At that point it is no longer the same Seq[NINODeletionConfig] type, rather it should be a type of something like Seq((NINO,ObjectId)).

That is unless you know an easier way, the bulk write can return document IDs but I am not sure that can be tied back to NINOs

2023-12-13 11:59 UTC, mahesh-hmrc commented
Thanks Dave! Yeah, think that's inline with what we discussed earlier and is already being factored into the models

2023-12-13 15:40 UTC, lutnos requested changes
You just need to actually audit the document IDs, not just the NINO, please

2023-12-13 15:40 UTC, lutnos commented on app/uk/gov/hmrc/helptosave/services/ApplicationStart.scala
> +        val ninos = deletedAccounts.map(_.nino).toList
We need to log not just the NINOs here, but the _id from EnrolmentData .

2023-12-13 15:40 UTC, lutnos commented on app/uk/gov/hmrc/helptosave/services/ApplicationStart.scala
> +        val ninos = undeletedAccounts.map(_.nino).toList
Ditto

2023-12-13 16:52 UTC, mahesh-hmrc commented
> You just need to actually audit the document IDs, not just the NINO, please

Yeah, sorted now. On back of our chat to revert on config, I accidentally reverted more than I should have. Included the code back in to audit doc id aswell. However, as part of that, felt it's clean to just keep the interface to NINODeletionConfig for ApplicationStart. Not ideal to change visibility of domain object outside of current `repo` scope

2023-12-14 09:20 UTC, lutnos approved these changes

2023-12-14 13:54 UTC, lutnos approved these changes

2023-12-14 15:01 UTC, merged